FROM golang:1.24-bookworm

ARG PROTOC_VERSION=25.1
ARG PROTOC_GEN_GO_VERSION=1.32.0
ARG PROTOC_GEN_TWIRP=8.1.3
ARG PROTOC_GEN_VALIDATE=1.0.2
ARG PROTOC_GEN_DOC_VERSION=1.5.1

WORKDIR /

# protoc
ADD https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip ./
RUN apt-get -q -y update && \
    apt-get -q -y install --no-install-recommends unzip && \
    unzip protoc-${PROTOC_VERSION}-linux-x86_64.zip -d ./usr/local && \
    rm protoc-${PROTOC_VERSION}-linux-x86_64.zip && \
    apt-get remove --purge -y unzip && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

# Go plugins for protoc
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v${PROTOC_GEN_GO_VERSION} && \
    go install github.com/twitchtv/twirp/protoc-gen-twirp@v${PROTOC_GEN_TWIRP} && \
    go install github.com/envoyproxy/protoc-gen-validate@v${PROTOC_GEN_VALIDATE}

# protoc-gen-doc for API documentation
RUN mkdir -p ${GOPATH}/src/github.com/pseudomuto/protoc-gen-doc && \
    curl -L https://github.com/pseudomuto/protoc-gen-doc/archive/v${PROTOC_GEN_DOC_VERSION}.tar.gz | tar xvz --strip 1 -C ${GOPATH}/src/github.com/pseudomuto/protoc-gen-doc
RUN cd ${GOPATH}/src/github.com/pseudomuto/protoc-gen-doc && \
    make build && \
    install -c ${GOPATH}/src/github.com/pseudomuto/protoc-gen-doc/protoc-gen-doc /go/bin/

ENTRYPOINT ["protoc", "--plugin=/go/bin/protoc-gen-go", "--plugin=/go/bin/protoc-gen-twirp", "--plugin=/go/bin/protoc-gen-validate", "--plugin=/go/bin/protoc-gen-doc"]
