version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: sblog-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sblog_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  migrate:
    build:
      context: .
      dockerfile: Dockerfile-migrate
    container_name: sblog-migrate
    depends_on:
      - postgres
    environment:
      - APP_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=sblog_dev
    volumes:
      - .:/app

  api:
    build:
      context: .
      dockerfile: Dockerfile-protogen
    container_name: sblog-api
    depends_on:
      - postgres
      - migrate
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5435
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=sblog_dev
    volumes:
      - .:/app
    restart: always

volumes:
  postgres_data:
