// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Content     string     `json:"content"`
	Excerpt     string     `json:"excerpt"`
	PublishedAt string     `json:"publishedAt"`
	Author      *Author    `json:"author"`
	Tags        []string   `json:"tags"`
	Likes       int        `json:"likes"`
	Comments    []*Comment `json:"comments"`
	ReadingTime *string    `json:"readingTime,omitempty"`
}

type Author struct {
	Name   string  `json:"name"`
	Avatar string  `json:"avatar"`
	Bio    *string `json:"bio,omitempty"`
}

type Comment struct {
	ID        string  `json:"id"`
	Content   string  `json:"content"`
	CreatedAt string  `json:"createdAt"`
	Author    *Author `json:"author"`
}

type Query struct {
}

type Tag struct {
	Name string `json:"name"`
}
